pipeline{
    agent any
    parameters{
      choice(choices: ['create', 'destroy'],name: 'action')
      string(name: 'InstanceName',trim: true )
    }
    environment{
        terraform = "/opt/homebrew/bin/terraform"
    }
    stages{
        stage('terraform'){
            steps{
                dir("vm"){
                    sh "${env.terraform} init"
                    sh "${env.terraform} fmt"
                    script{
                        if (params.action == "create") {
                            sh "${env.terraform} apply -var='tags-name=${params.InstanceName}' -var-file='dev.tfvars' -auto-approve"
                        }else if (params.action == "destroy") {
                            sh "${env.terraform} destroy -var='tags-name=${params.InstanceName}' -var-file='dev.tfvars' -auto-approve"
                        }
                    }
                }
            }
        }
    }
}